/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td3.visiteurs;

import org.junit.Test;
import td3.visiteurs.main.Main;

import static org.junit.Assert.*;

public class AppTest {

}
