/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td4.state;

import org.checkerframework.checker.units.qual.A;

public class App {

    public static void main(String[] args) {

        AmpouleContext ampouleContext = new AmpouleContext();
        ampouleContext.setAllumee();
        ampouleContext.setEteinte();
        ampouleContext.setAllumee();
        ampouleContext.setAllumee();
        ampouleContext.setEteinte();
        ampouleContext.setCassee();

    }
}
