/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td5.strategy;

import td5.strategy.context.Unite;
import td5.strategy.strategyA.Voler;
import td5.strategy.strategyB.Canon;

import java.util.List;

public class App {

    public static void main(String[] args) {
        Unite unite = new Unite();
        unite.setAttaque(new Canon());
        unite.setDeplacement(new Voler());
        unite.attaquer();
        unite.seDeplacer();
    }
}
